// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmfeeaggtzdieowkwmws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZmVlYWdndHpkaWVvd2t3bXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDYyOTksImV4cCI6MjA2OTg4MjI5OX0.3a2kGrz-_reG0e7RVjzscIAOWoPVBI4cEr1oG60RVIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});